services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: habileo-backend-dev
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - FLASK_DEBUG=1
    volumes:
      - ./backend:/app
    command: ["python", "run.py"]
    networks:
      - habileo

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: habileo-frontend-dev
    restart: unless-stopped
    ports:
      - "8100:8100"
    volumes:
      - ./front:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - habileo

networks:
  habileo:
    driver: bridge
